
/*........................

Copyright (c) 2022, FlamencoTech India Pvt. Ltd.
All rights reserved.

file:  adminConstants.jsx

Brief:  It contains Constants related to admin. 

Project: Pixel Sensor

Release version: version 1.0.0

Release Date: Dec 14, 2022

Auther: Mohak Tripathi

Whats New: Everything.
 ..........................*/

export const VARIANT_REQUEST =  "VARIANT_REQUEST"
export const VARIANT_SUCCESS = "VARIANT_SUCCESS"
export const VARIANT_FAIL = "VARIANT_FAIL"





export const AP_MODE_SSID_PASS_REQUEST =  "AP_MODE_SSID_PASS_REQUEST"
export const AP_MODE_SSID_PASS_SUCCESS = "AP_MODE_SSID_PASS_SUCCESS"
export const AP_MODE_SSID_PASS_FAIL = "AP_MODE_SSID_PASS_FAIL"


export const CLEAR_ERRORS_VARIANT = "CLEAR_ERRORS_VARIANT"
export const CLEAR_SUCCESS_VARIANT  = 'CLEAR_SUCCESS_VARIANT'

export const CLEAR_ERRORS_SSID_PASS = "CLEAR_ERRORS_SSID_PASS"
export const CLEAR_SUCCESS_SSID_PASS = 'CLEAR_SUCCESS_SSID_PASS'


export const AP_MODE_REQUEST = "AP_MODE_REQUEST"
export const AP_MODE_SUCCESS = "AP_MODE_SUCCESS"
export const AP_MODE_FAIL = "AP_MODE_FAIL"

export const CLEAR_ERRORS_APMODE = "CLEAR_ERRORS_APMODE"
export const CLEAR_SUCCESS_APMODE = 'CLEAR_SUCCESS_APMODE'


export const ADMIN_WIFI_REQUEST =  "ADMIN_WIFI_REQUEST"
export const ADMIN_WIFI_SUCCESS = "ADMIN_WIFI_SUCCESS"
export const ADMIN_WIFI_FAIL = "ADMIN_WIFI_FAIL"


export const CLEAR_ERRORS_WIFI_STATUS = "CLEAR_ERRORS_WIFI_STATUS"
export const CLEAR_SUCCESS_WIFI_STATUS  = 'CLEAR_SUCCESS_WIFI_STATUS'


export const ADMIN_SSH_REQUEST =  "ADMIN_SSH_REQUEST"
export const ADMIN_SSH_SUCCESS = "ADMIN_SSH_SUCCESS"
export const ADMIN_SSH_FAIL = "ADMIN_SSH_FAIL"
export const CLEAR_ERRORS_SSH_STATUS = "CLEAR_ERRORS_SSH_STATUS"
export const CLEAR_SUCCESS_SSH_STATUS  = 'CLEAR_SUCCESS_SSH_STATUS'

export const ADMIN_VNC_REQUEST =  "ADMIN_VNC_REQUEST"
export const ADMIN_VNC_SUCCESS = "ADMIN_VNC_SUCCESS"
export const ADMIN_VNC_FAIL = "ADMIN_VNC_FAIL"
export const CLEAR_ERRORS_VNC_STATUS = "CLEAR_ERRORS_VNC_STATUS"
export const CLEAR_SUCCESS_VNC_STATUS  = 'CLEAR_SUCCESS_VNC_STATUS'


export const GET_ADMIN_INFO_REQUEST =  "GET_ADMIN_INFO_REQUEST"
export const GET_ADMIN_INFO_SUCCESS = "GET_ADMIN_INFO_SUCCESS"
export const GET_ADMIN_INFO_FAIL = "GET_ADMIN_INFO_FAIL"

export const OTA_REQUEST =  "OTA_REQUEST"
export const OTA_SUCCESS = "OTA_SUCCESS"
export const OTA_FAIL = "OTA_FAIL"
export const CLEAR_ERRORS_OTA = "CLEAR_ERRORS_OTA"
export const CLEAR_SUCCESS_OTA  = 'CLEAR_SUCCESS_OTA'

export const GET_APMODE_APPLY_REQUEST =  "GET_APMODE_APPLY_REQUEST"
export const GET_APMODE_APPLY_SUCCESS = "GET_APMODE_APPLY_SUCCESS"
export const GET_APMODE_APPLY_FAIL = "GET_APMODE_APPLY_FAIL"
export const CLEAR_ERRORS_APMODE_APPLY_STATUS = "CLEAR_ERRORS_APMODE_APPLY_STATUS"
export const CLEAR_SUCCESS_APMODE_APPLY_STATUS  = 'CLEAR_SUCCESS_APMODE_APPLY_STATUS'



export const GET_APMODEPASS_APPLY_REQUEST =  "GET_APMODEPASS_APPLY_REQUEST"
export const GET_APMODEPASS_APPLY_SUCCESS = "GET_APMODEPASS_APPLY_SUCCESS"
export const GET_APMODEPASS_APPLY_FAIL = "GET_APMODEPASS_APPLY_FAIL"
export const CLEAR_ERRORS_APMODEPASS_APPLY_STATUS = "CLEAR_ERRORS_APMODEPASS_APPLY_STATUS"
export const CLEAR_SUCCESS_APMODEPASS_APPLY_STATUS  = 'CLEAR_SUCCESS_APMODEPASS_APPLY_STATUS'

export const GET_WIFI_STATUS_APPLY_REQUEST =  "GET_WIFI_STATUS_APPLY_REQUEST"
export const GET_WIFI_STATUS_APPLY_SUCCESS = "GET_WIFI_STATUS_APPLY_SUCCESS"
export const GET_WIFI_STATUS_APPLY_FAIL = "GET_WIFI_STATUS_APPLY_FAIL"
export const CLEAR_ERRORS_WIFI_APPLY_STATUS = "CLEAR_ERRORS_WIFI_APPLY_STATUS"
export const CLEAR_SUCCESS_WIFI_APPLY_STATUS  = 'CLEAR_SUCCESS_WIFI_APPLY_STATUS'

export const GET_VARIANT_STATUS_APPLY_REQUEST =  "GET_VARIANT_STATUS_APPLY_REQUEST"
export const GET_VARIANT_STATUS_APPLY_SUCCESS = "GET_VARIANT_STATUS_APPLY_SUCCESS"
export const GET_VARIANT_STATUS_APPLY_FAIL = "GET_VARIANT_STATUS_APPLY_FAIL"
export const CLEAR_ERRORS_VARIANT_APPLY_STATUS = "CLEAR_ERRORS_VARIANT_APPLY_STATUS"
export const CLEAR_SUCCESS_VARIANT_APPLY_STATUS  = 'CLEAR_SUCCESS_VARIANT_APPLY_STATUS'

export const GET_SSH_STATUS_APPLY_REQUEST =  "GET_SSH_STATUS_APPLY_REQUEST"
export const GET_SSH_STATUS_APPLY_SUCCESS = "GET_SSH_STATUS_APPLY_SUCCESS"
export const GET_SSH_STATUS_APPLY_FAIL = "GET_SSH_STATUS_APPLY_FAIL"
export const CLEAR_ERRORS_SSH_APPLY_STATUS = "CLEAR_ERRORS_SSH_APPLY_STATUS"
export const CLEAR_SUCCESS_SSH_APPLY_STATUS  = 'CLEAR_SUCCESS_SSH_APPLY_STATUS'

export const GET_VNC_STATUS_APPLY_REQUEST =  "GET_VNC_STATUS_APPLY_REQUEST"
export const GET_VNC_STATUS_APPLY_SUCCESS = "GET_VNC_STATUS_APPLY_SUCCESS"
export const GET_VNC_STATUS_APPLY_FAIL = "GET_VNC_STATUS_APPLY_FAIL"
export const CLEAR_ERRORS_VNC_APPLY_STATUS = "CLEAR_ERRORS_VNC_APPLY_STATUS"
export const CLEAR_SUCCESS_VNC_APPLY_STATUS  = 'CLEAR_SUCCESS_VNC_APPLY_STATUS'


export const GET_OTA_APPLY_REQUEST =  "GET_OTA_APPLY_REQUEST"
export const GET_OTA_APPLY_SUCCESS = "GET_OTA_APPLY_SUCCESS"
export const GET_OTA_APPLY_FAIL = "GET_OTA_APPLY_FAIL"
export const CLEAR_ERRORS_OTA_APPLY = "CLEAR_ERRORS_OTA_APPLY"
export const CLEAR_SUCCESS_OTA_APPLY  = 'CLEAR_SUCCESS_OTA_APPLY'