

/*........................

Copyright (c) 2022, FlamencoTech India Pvt. Ltd.
All rights reserved.

file:  networkConstants.jsx

Brief:  It contains Constants related to network page. 

Project: Pixel Sensor

Release version: version 1.0.0

Release Date: Dec 14, 2022

Auther: Mohak Tripathi

Whats New: Everything.
 ..........................*/

 export const WIFICRED_NETWORK_REQUEST = "WIFICRED_NETWORK_REQUEST"
 export const WIFICRED_NETWORK_SUCCESS = "WIFICRED_NETWORK_SUCCESS"
 export const WIFICRED_NETWORK_FAIL = "WIFICRED_NETWORK_FAIL"
 
 export const CLEAR_ERRORS_CRED = "CLEAR_ERRORS_CRED"
 export const CLEAR_SUCCESS_CRED = 'CLEAR_SUCCESS_CRED'


export const NTP_NETWORK_REQUEST = "NTP_NETWORK_REQUEST"
export const NTP_NETWORK_SUCCESS = "NTP_NETWORK_SUCCESS"
export const NTP_NETWORK_FAIL = "NTP_NETWORK_FAIL"

export const CLEAR_ERRORS_NTP = "CLEAR_ERRORS_NTP"
export const CLEAR_SUCCESS_NTP = 'CLEAR_SUCCESS_NTP'

export const WIFI_NETWORK_REQUEST = "WIFI_NETWORK_REQUEST"
export const WIFI_NETWORK_SUCCESS = "WIFI_NETWORK_SUCCESS"
export const WIFI_NETWORK_FAIL = "WIFI_NETWORK_FAIL"

export const CLEAR_ERRORS_CRED_WIFI_NET = "CLEAR_ERRORS_CRED_WIFI_NET"
export const CLEAR_SUCCESS_CRED_WIFI_NET = 'CLEAR_SUCCESS_CRED_WIFI_NET'






export const GET_NETWORK_INFO_REQUEST = "GET_NETWORK_INFO_REQUEST"
export const GET_NETWORK_INFO_SUCCESS = "GET_NETWORK_INFO_SUCCESS"
export const GET_NETWORK_INFO_FAIL = "GET_NETWORK_INFO_FAIL"


export const WIFICRED_APPLY_REQUEST = "WIFICRED_APPLY_REQUEST"
export const WIFICRED_APPLY_SUCCESS = "WIFICRED_APPLY_SUCCESS"
export const WIFICRED_APPLY_FAIL = "WIFICRED_APPLY_FAIL"

export const CLEAR_ERRORS_CRED_WIFI_APPLY = "CLEAR_ERRORS_CRED_WIFI_APPLY"
export const CLEAR_SUCCESS_CRED_WIFI_APPLY = 'CLEAR_SUCCESS_CRED_WIFI_APPLY'

export const STATICIP_APPLY_REQUEST = "STATICIP_APPLY_REQUEST"
export const STATICIP_APPLY_SUCCESS = "STATICIP_APPLY_SUCCESS"
export const STATICIP_APPLY_FAIL = "STATICIP_APPLY_FAIL"
export const CLEAR_ERRORS_STATICIP_APPLY = "CLEAR_ERRORS_STATICIP_APPLY"
export const CLEAR_SUCCESS_STATICIP_APPLY = 'CLEAR_SUCCESS_STATICIP_APPLY'

export const NTP_APPLY_REQUEST = "NTP_APPLY_REQUEST"
export const NTP_APPLY_SUCCESS = "NTP_APPLY_SUCCESS"
export const NTP_APPLY_FAIL = "NTP_APPLY_FAIL"

export const CLEAR_ERRORS_NTP_APPLY = "CLEAR_ERRORS_NTP_APPLY"
export const CLEAR_SUCCESS_NTP_APPLY = 'CLEAR_SUCCESS_NTP_APPLY'
