/*........................

Copyright (c) 2022, FlamencoTech India Pvt. Ltd.
All rights reserved.

file:  serviceConstants.jsx

Brief:  It contains Constants related to service page. 

Project: Pixel Sensor

Release version: version 1.0.0

Release Date: Dec 14, 2022

Auther: Mohak Tripathi

Whats New: Everything.
 ..........................*/


export const GET_SERVICE_STATUS_REQUEST =  "GET_SERVICE_STATUS_REQUEST"
export const GET_SERVICE_STATUS_SUCCESS = "GET_SERVICE_STATUS_SUCCESS"
export const GET_SERVICE_STATUS_FAIL = "GET_SERVICE_STATUS_FAIL"

export const SERVICE_CONFIG_REQUEST =  "SERVICE_CONFIG_REQUEST"
export const SERVICE_CONFIG_SUCCESS = "SERVICE_CONFIG_SUCCESS"
export const SERVICE_CONFIG_FAIL = "SERVICE_CONFIG_FAIL"

export const SERVICE_OCCUPANCY_REQUEST =  "SERVICE_OCCUPANCY_REQUEST"
export const SERVICE_OCCUPANCY_SUCCESS = "SERVICE_OCCUPANCY_SUCCESS"
export const SERVICE_OCCUPANCY_FAIL = "SERVICE_OCCUPANCY_FAIL"

export const SERVICE_PEOPLECOUNT_REQUEST =  "SERVICE_PEOPLECOUNT_REQUEST"
export const SERVICE_PEOPLECOUNT_SUCCESS = "SERVICE_PEOPLECOUNT_SUCCESS"
export const SERVICE_PEOPLECOUNT_FAIL = "SERVICE_PEOPLECOUNT_FAIL"

export const SERVICE_PEOPLECOUNT_SERVICE_ONBOOT_REQUEST =  "SERVICE_PEOPLECOUNT_SERVICE_ONBOOT_REQUEST"
export const SERVICE_PEOPLECOUNT_SERVICE_ONBOOT_SUCCESS = "SERVICE_PEOPLECOUNT_SERVICE_ONBOOT_SUCCESS"
export const SERVICE_PEOPLECOUNT_SERVICE_ONBOOT_FAIL = "SERVICE_PEOPLECOUNT_SERVICE_ONBOOT_FAIL"

export const SERVICE_ANALYZER_REQUEST =  "SERVICE_ANALYZER_REQUEST"
export const SERVICE_ANALYZER_SUCCESS = "SERVICE_ANALYZER_SUCCESS"
export const SERVICE_ANALYZER_FAIL = "SERVICE_ANALYZER_FAIL"

export const SERVICE_OCCUPANCYCOUNT_REQUEST =  "SERVICE_OCCUPANCYCOUNT_REQUEST"
export const SERVICE_OCCUPANCYCOUNT_SUCCESS = "SERVICE_OCCUPANCYCOUNT_SUCCESS"
export const SERVICE_OCCUPANCYCOUNT_FAIL = "SERVICE_OCCUPANCYCOUNT_FAIL"


export const REBOOT_VARIANT_REQUEST =  "REBOOT_VARIANT_REQUEST"
export const REBOOT_VARIANT_SUCCESS = "REBOOT_VARIANT_SUCCESS"
export const REBOOT_VARIANT_FAIL ="REBOOT_VARIANT_FAIL"




export const CLEAR_ERRORS_CONFIG = "CLEAR_ERRORS_CONFIG"
export const CLEAR_SUCCESS_CONFIG  = 'CLEAR_SUCCESS_CONFIG'

export const CLEAR_ERRORS_OCCUPANCY = "CLEAR_ERRORS_OCCUPANCY"
export const CLEAR_SUCCESS_OCCUPANCY  = 'CLEAR_SUCCESS_OCCUPANCY'

export const CLEAR_ERRORS_PEOPLECOUNT = "CLEAR_ERRORS_PEOPLECOUNT"
export const CLEAR_SUCCESS_PEOPLECOUNT  = 'CLEAR_SUCCESS_PEOPLECOUNT'

export const CLEAR_ERRORS_PEOPLEBOOT = "CLEAR_ERRORS_PEOPLEBOOT"
export const CLEAR_SUCCESS_PEOPLEBOOT  = 'CLEAR_SUCCESS_PEOPLEBOOT'

export const CLEAR_ERRORS_ANALYZER= "CLEAR_ERRORS_ANALYZER"
export const CLEAR_SUCCESS_ANALYZER  = 'CLEAR_SUCCESS_ANALYZER'
 
export const CLEAR_ERRORS_OCCUPANCYCOUNT= "CLEAR_ERRORS_OCCUPANCYCOUNT"
export const CLEAR_SUCCESS_OCCUPANCYCOUNT  = 'CLEAR_SUCCESS_OCCUPANCYCOUNT'
 
